<?php
declare(strict_types=1);

/**
 * Menü PDF'inden kırpılan fotoğraflar (uploads/menu, uploads/gallery, uploads/slider).
 * Özgün fotoğraf dosyaları gelirse panelden değiştirilir.
 * ob_seed(): ürünlere ada göre bağlanır; galeri ve slaytlar yalnız tablo boşsa eklenir.
 */
return [
    'items' => [
        'BBQ Chicken Wings' => 'uploads/menu/bbq-chicken-wings.jpg',
        'Fried Chicken Wings' => 'uploads/menu/fried-chicken-wings.jpg',
        'Babil Adana Dürüm' => 'uploads/menu/babil-adana-durum.jpg',
        'Izgara Tavuk Pirzola' => 'uploads/menu/izgara-tavuk-pirzola.jpg',
        'Özel Babyloon Çıtır Dürüm' => 'uploads/menu/ozel-babyloon-citir-durum.jpg',
        'Cheddarlı Tavuk Dürüm' => 'uploads/menu/cheddarli-tavuk-durum.jpg',
        'Kıymalı Kaşarlı Dürüm' => 'uploads/menu/kiymali-kasarli-durum.jpg',
        'Cheddarlı Köfte Dürüm' => 'uploads/menu/cheddarli-kofte-durum.jpg',
        'Adana Köfte Dürüm' => 'uploads/menu/adana-kofte-durum.jpg',
        'Kıbrıs Köfte Dürüm' => 'uploads/menu/kibris-kofte-durum.jpg',
        'Karışık Tost' => 'uploads/menu/karisik-tost.jpg',
        'Cheese Burger' => 'uploads/menu/cheese-burger.jpg',
        'Kumru Burger' => 'uploads/menu/kumru-burger.jpg',
        'Meksikan Burger' => 'uploads/menu/meksikan-burger.jpg',
        'Cyprus Burger' => 'uploads/menu/cyprus-burger.jpg',
        'Chef Burger' => 'uploads/menu/chef-burger.jpg',
        'Izgara Kasap Köfte' => 'uploads/menu/izgara-kasap-kofte.jpg',
        'Soslu Tavuk Kanat Izgara' => 'uploads/menu/soslu-tavuk-kanat-izgara.jpg',
        'Tavuk Straganof' => 'uploads/menu/tavuk-straganof.jpg',
        'Izgara Tavuk Bonfile' => 'uploads/menu/izgara-tavuk-bonfile.jpg',
        'Ton Balıklı Sandviç' => 'uploads/menu/ton-balikli-sandvic.jpg',
        'Et Fajita Servis' => 'uploads/menu/et-fajita-servis.jpg',
        'Tavuk Fajita Servis' => 'uploads/menu/tavuk-fajita-servis.jpg',
        'Mantı' => 'uploads/menu/manti.jpg',
        'Alfredo Penne Pasta' => 'uploads/menu/alfredo-penne-pasta.jpg',
        'Spagetti Bolognese' => 'uploads/menu/spagetti-bolognese.jpg',
        'Ton Balıklı Salata' => 'uploads/menu/ton-balikli-salata.jpg',
        'Serpme Kahvaltı' => 'uploads/menu/serpme-kahvalti.jpg',
        'Kahvaltı Tabağı' => 'uploads/menu/kahvalti-tabagi.jpg',
        'Sıcak Kahvaltı' => 'uploads/menu/sicak-kahvalti.jpg',
        'Hellim Izgara (4 dilim)' => 'uploads/menu/hellim-izgara-4-dilim.jpg',
        'Sade Yumurta' => 'uploads/menu/sade-yumurta.jpg',
        'Sade Menemen' => 'uploads/menu/sade-menemen.jpg',
        'Sosisli Omlet' => 'uploads/menu/sosisli-omlet.jpg',
        'Dondurmalı Sufle' => 'uploads/menu/dondurmali-sufle.jpg',
        'Sütlaç' => 'uploads/menu/sutlac.jpg',
        'Trileçe' => 'uploads/menu/trilece.jpg',
        'Kazandibi' => 'uploads/menu/kazandibi.jpg',
        'Karamelli Trileçe' => 'uploads/menu/karamelli-trilece.jpg',
        'Tiramisu' => 'uploads/menu/tiramisu.jpg',
        'Limonlu Cheesecake' => 'uploads/menu/limonlu-cheesecake.jpg',
        'Vanilyalı Krep Pasta' => 'uploads/menu/vanilyali-krep-pasta.jpg',
        'Limonlu Molten Kek' => 'uploads/menu/limonlu-molten-kek.jpg',
        'Karamelize Bisküvili Pasta' => 'uploads/menu/karamelize-biskuvili-pasta.jpg',
        'Fıstık Rüyası' => 'uploads/menu/fistik-ruyasi.jpg',
        'Kremalı Havuçlu Kek' => 'uploads/menu/kremali-havuclu-kek.jpg',
        'Kahveli Krep Pasta' => 'uploads/menu/kahveli-krep-pasta.jpg',
        'Meyveli Magnolya' => 'uploads/menu/meyveli-magnolya.jpg',
        'Muzlu Magnolya' => 'uploads/menu/muzlu-magnolya.jpg',
        'Meyveli Waffle' => 'uploads/menu/meyveli-waffle.jpg',
        'Mozaik Pasta' => 'uploads/menu/mozaik-pasta.jpg',
        'Dondurma' => 'uploads/menu/dondurma.jpg',
        'Dondurmalı Çilek Kasesi' => 'uploads/menu/dondurmali-cilek-kasesi.jpg',
        'Çikolatalı Milkshake' => 'uploads/menu/cikolatali-milkshake.jpg',
        'Lemon Chillers' => 'uploads/menu/lemon-chillers.jpg',
        'Karadut Smoothie' => 'uploads/menu/karadut-smoothie.jpg',
        'Latte Bubble' => 'uploads/menu/latte-bubble.jpg',
        'İtalyan Soda Mavi Melek' => 'uploads/menu/italyan-soda-mavi-melek.jpg',
        'Soya Soslu Tavuk' => 'uploads/menu/soya-soslu-tavuk.jpg',
        'Limon Soslu Tavuk' => 'uploads/menu/limon-soslu-tavuk.jpg',
        'Limon Soslu Et' => 'uploads/menu/limon-soslu-et.jpg',
        'Coconut Cream Chicken' => 'uploads/menu/coconut-cream-chicken.jpg',
        'Grilled Chicken Breast' => 'uploads/menu/grilled-chicken-breast.jpg',
        'Fried Chicken Goujons' => 'uploads/menu/fried-chicken-goujons.jpg',
        'Beef Wrap' => 'uploads/menu/beef-wrap.jpg',
        'Chicken Wrap' => 'uploads/menu/chicken-wrap.jpg',
        'Cream Garlic Chicken Penne' => 'uploads/menu/cream-garlic-chicken-penne.jpg',
        'Cream Garlic Chicken' => 'uploads/menu/cream-garlic-chicken.jpg',
        'BBQ Beef Pizza' => 'uploads/menu/bbq-beef-pizza.jpg',
        'BBQ Chicken Pizza' => 'uploads/menu/bbq-chicken-pizza.jpg',
        'Babil İskender' => 'uploads/menu/babil-iskender.jpg',
        'Babil Acılı Et' => 'uploads/menu/babil-acili-et.jpg',
        'Soya Soslu Et' => 'uploads/menu/soya-soslu-et.jpg',
    ],
    'gallery' => [
        ['uploads/gallery/p08-1.jpg', 'Babil İskender'],
        ['uploads/gallery/p17-1.jpg', 'Kumru Burger'],
        ['uploads/gallery/p02-1.jpg', 'Soya Soslu Tavuk'],
        ['uploads/gallery/p25-1.jpg', 'Mantı'],
        ['uploads/gallery/p20-1.jpg', 'Izgara Kasap Köfte'],
        ['uploads/gallery/p05-1.jpg', 'Beef Wrap'],
        ['uploads/gallery/p24-1.jpg', 'Et Fajita Servis'],
        ['uploads/gallery/p27-1.jpg', 'Serpme Kahvaltı'],
        ['uploads/gallery/p16-1.jpg', 'Cheese Burger'],
        ['uploads/gallery/p26-2.jpg', 'Spagetti Bolognese'],
        ['uploads/gallery/p28-3.jpg', 'Hellim Izgara (4 dilim)'],
        ['uploads/gallery/p33-2.jpg', 'Dondurmalı Çilek Kasesi'],
        ['uploads/gallery/p07-1.jpg', 'BBQ Beef Pizza'],
        ['uploads/gallery/p30-1.jpg', 'Dondurmalı Sufle'],
        ['uploads/gallery/p11-1.jpg', 'Babil Adana Dürüm'],
        ['uploads/gallery/p32-1.jpg', 'Meyveli Magnolya'],
        ['uploads/gallery/p12-1.jpg', 'Özel Babyloon Çıtır Dürüm'],
        ['uploads/gallery/p35-1.jpg', 'Latte Bubble'],
        ['uploads/gallery/p37-1.jpg', null],
        ['uploads/gallery/p38-1.jpg', null],
    ],
    'slides' => ['uploads/slider/hero-1.jpg', 'uploads/slider/hero-2.jpg'],
];
