<?php
declare(strict_types=1);

/**
 * Old Babyloon menüsü — müşterinin PDF menüsünden (babyloon-03.08.2026-1.pdf, 40 sayfa)
 * yazıya döküldü. Fiyatlar birebir; yalnızca bariz yazım hataları düzeltildi.
 * ob_seed() menü tabloları boşsa bunu yükler. Sonrasında panel esastır.
 *
 * Biçim: [slug, ad_tr, ad_en, açıklama_tr, açıklama_en, ikon, [ürünler]]
 */
return [
    ['yeni', 'Yeni Lezzetler', 'New Dishes', 'Menümüze yeni eklenenler', 'Just added to our menu', 'star', [
        ['name_tr' => 'Soya Soslu Tavuk', 'name_en' => 'Soy Sauce Chicken', 'description_tr' => 'Özel baharatlarla marine edilmiş tavuk, soya sosu, yeşil biber, kapya biber, mantar, salata, cips ve pilav ile servis edilir.', 'description_en' => 'Chicken marinated in special spices, soy sauce, green pepper, red pepper and mushrooms; served with salad, chips and rice.', 'price' => 700],
        ['name_tr' => 'Limon Soslu Tavuk', 'name_en' => 'Lemon Sauce Chicken', 'description_tr' => 'Limon marineli tavuk, kapya biber, yeşil biber, mantar, krema, salata, pilav ve cips ile servis edilir.', 'description_en' => 'Lemon-marinated chicken, red pepper, green pepper, mushrooms and cream; served with salad, rice and chips.', 'price' => 700],
        ['name_tr' => 'Limon Soslu Et', 'name_en' => 'Lemon Sauce Beef', 'description_tr' => 'Dana bonfile, çarliston biber, kapya biber, mantar, krema, limon ve özel baharatlar; salata, cips ve pilav ile servis edilir.', 'description_en' => 'Beef tenderloin, Charleston pepper, red pepper, mushrooms, cream, lemon and special spices; served with salad, chips and rice.', 'price' => 750],
        ['name_tr' => 'Coconut Cream Chicken', 'name_en' => 'Coconut Cream Chicken', 'description_tr' => 'Marine edilmiş tavuk bonfile, yeşil biber, kapya biber, mantar, hindistan cevizi, krema, özel baharatlar, salata, cips ve pilav ile servis edilir.', 'description_en' => 'Marinated chicken fillet, green pepper, red pepper, mushrooms, coconut, cream and special spices; served with salad, chips and rice.', 'price' => 700],
        ['name_tr' => 'Grilled Chicken Breast', 'name_en' => 'Grilled Chicken Breast', 'description_tr' => 'Özel baharatlarla marine edilmiş tavuk göğsü, salata, cips ve pilav ile servis edilir.', 'description_en' => 'Chicken breast marinated in special spices; served with salad, chips and rice.', 'price' => 700],
        ['name_tr' => 'Fried Chicken Goujons', 'name_en' => 'Fried Chicken Goujons', 'description_tr' => 'Fritözde çıtır çıtır tavuk, panelenmiş tavuk bonfileleri, salata, cips ve pilav ile servis edilir.', 'description_en' => 'Crispy breaded chicken fillets; served with salad, chips and rice.', 'price' => 700],
        ['name_tr' => 'Beef Wrap', 'name_en' => 'Beef Wrap', 'description_tr' => 'Özel baharatlarla marine edilmiş dana bonfile, yeşil biber, kapya biber, mantar, eritilmiş peynir, soya sos, cips ve salata ile servis edilir.', 'description_en' => 'Beef tenderloin marinated in special spices, green pepper, red pepper, mushrooms, melted cheese and soy sauce; served with chips and salad.', 'price' => 660],
        ['name_tr' => 'Chicken Wrap', 'name_en' => 'Chicken Wrap', 'description_tr' => 'Soya sos, özel baharatlar, kapya biber, yeşil biber, mantar, eritilmiş peynir, salata ve cips ile servis edilir.', 'description_en' => 'Soy sauce, special spices, red pepper, green pepper, mushrooms and melted cheese; served with salad and chips.', 'price' => 570],
        ['name_tr' => 'Cream Garlic Chicken Penne', 'name_en' => 'Cream Garlic Chicken Penne', 'description_tr' => 'Penne makarna, marine tavuk, çarliston biber, kapya biber, mantar, özel baharatlar, krema, parmesan peyniri ile servis edilir.', 'description_en' => 'Penne pasta, marinated chicken, Charleston pepper, red pepper, mushrooms, special spices and cream; served with parmesan.', 'price' => 550],
        ['name_tr' => 'Cream Garlic Chicken', 'name_en' => 'Cream Garlic Chicken', 'description_tr' => 'Marine edilmiş tavuk, yeşil biber, mantar, kapya biber, sarımsaklı krema, cips, salata, ve pilav ile servis edilir.', 'description_en' => 'Marinated chicken, green pepper, mushrooms, red pepper and garlic cream; served with chips, salad and rice.', 'price' => 700],
        ['name_tr' => 'BBQ Beef Pizza', 'name_en' => 'BBQ Beef Pizza', 'description_tr' => 'Julyen bonfile dana eti, mantar, soğan, domates, yeşil biber, kapya biber, pizza peyniri ve BBQ sos.', 'description_en' => 'Julienned beef tenderloin, mushrooms, onion, tomato, green pepper, red pepper, pizza cheese and BBQ sauce.', 'price' => 780],
        ['name_tr' => 'BBQ Chicken Pizza', 'name_en' => 'BBQ Chicken Pizza', 'description_tr' => 'Marine tavuk, mantar, yeşil biber, soğan, kapya biber, domates, pizza peyniri ve BBQ sos.', 'description_en' => 'Marinated chicken, mushrooms, green pepper, onion, red pepper, tomato, pizza cheese and BBQ sauce.', 'price' => 740],
        ['name_tr' => 'Babil İskender', 'name_en' => 'Babil İskender Kebab', 'description_tr' => 'İskender özel ekmeği, ızgara kasap köfte, iskender sos, ızgara biber ve yoğurt ile servis edilir.', 'description_en' => 'Special İskender bread, grilled butcher’s meatballs, İskender sauce, grilled pepper and yoghurt.', 'price' => 750],
        ['name_tr' => 'Babil Acılı Et', 'name_en' => 'Babil Spicy Beef', 'description_tr' => 'Marine edilmiş dana eti, çarliston biber, kapya biber, mantar, salsa sos, domates sos; pilav, cips ve salata ile servis edilir.', 'description_en' => 'Marinated beef, Charleston pepper, red pepper, mushrooms, salsa and tomato sauce; served with rice, chips and salad.', 'price' => 750],
        ['name_tr' => 'Soya Soslu Et', 'name_en' => 'Soy Sauce Beef', 'description_tr' => 'Özel baharatlarla marine edilmiş dana bonfile, kapya biber, yeşil biber, mantar, soya sos, pilav, salata ve cips ile servis edilir.', 'description_en' => 'Beef tenderloin marinated in special spices, red pepper, green pepper, mushrooms and soy sauce; served with rice, salad and chips.', 'price' => 750],
        ['name_tr' => 'BBQ Chicken Wings', 'name_en' => 'BBQ Chicken Wings', 'description_tr' => 'Özel baharatlarla marine edilmiş dökme but kanat, wok tavada pişirilmiş BBQ sos ve susam, salata, cips ve pilav ile servis edilir.', 'description_en' => 'Chicken wings marinated in special spices, wok-cooked with BBQ sauce and sesame; served with salad, chips and rice.', 'price' => 730],
        ['name_tr' => 'Fried Chicken Wings', 'name_en' => 'Fried Chicken Wings', 'description_tr' => 'Fritözde çıtır çıtır panelenmiş tavuk but kanat, salata, cips ve pilav ile servis edilir.', 'description_en' => 'Crispy breaded chicken wings; served with salad, chips and rice.', 'price' => 730],
        ['name_tr' => 'Babil Adana Dürüm', 'name_en' => 'Babil Adana Wrap', 'description_tr' => 'Özel baharatlarla çekilmiş dana kıyma, soğan, yeşillik, cips, kornişon turşu, domates, maydanoz, Babil sos; salata ve cips ile servis edilir.', 'description_en' => 'Hand-minced beef with special spices, onion, greens, chips, gherkins, tomato, parsley and Babil sauce; served with salad and chips.', 'price' => 520],
        ['name_tr' => 'Izgara Tavuk Pirzola', 'name_en' => 'Grilled Chicken Chops', 'description_tr' => 'Özel baharatlarla marine edilmiş tavuk pirzola, cips, salata ve pilav ile servis edilir.', 'description_en' => 'Chicken chops marinated in special spices; served with chips, salad and rice.', 'price' => 700],
    ]],
    ['durum', 'Dürüm & Meksika', 'Wraps & Mexican', null, null, 'plate', [
        ['name_tr' => 'Özel Babyloon Çıtır Dürüm', 'name_en' => 'Babyloon Special Crispy Wrap', 'description_tr' => 'Çıtır tortilla içerisinde tavuk, yeşil biber, kaşar peyniri, salsa sos, cips, mevsim yeşillikleri.', 'description_en' => 'Crispy tortilla filled with chicken, green pepper, kashar cheese, salsa, chips and seasonal greens.', 'price' => 520, 'group_tr' => 'Dürümler', 'group_en' => 'Wraps'],
        ['name_tr' => 'Cheddarlı Tavuk Dürüm', 'name_en' => 'Cheddar Chicken Wrap', 'description_tr' => 'Izgara tavuk bonfile, cheddar peyniri, patates, karamelize domates, Babyloon sos, salata ve cips ile servis edilir.', 'description_en' => 'Grilled chicken fillet, cheddar, potato, caramelised tomato and Babyloon sauce; served with salad and chips.', 'price' => 520, 'group_tr' => 'Dürümler', 'group_en' => 'Wraps'],
        ['name_tr' => 'Kıymalı Kaşarlı Dürüm', 'name_en' => 'Minced Beef & Cheese Wrap', 'description_tr' => 'Tortilla lavaş, kavrulmuş kıyma içerisinde rendelenmiş kaşar peyniri, salata ve cips ile', 'description_en' => 'Tortilla wrap with sautéed minced beef and grated kashar cheese; served with salad and chips.', 'price' => 600, 'group_tr' => 'Dürümler', 'group_en' => 'Wraps'],
        ['name_tr' => 'Cheddarlı Köfte Dürüm', 'name_en' => 'Cheddar Meatball Wrap', 'description_tr' => '120 gr ızgara köfte, cheddar peyniri, ızgara domates, patates, Babyloon sos, salata ve cips ile', 'description_en' => '120 g grilled meatball, cheddar, grilled tomato, potato and Babyloon sauce; served with salad and chips.', 'price' => 520, 'group_tr' => 'Dürümler', 'group_en' => 'Wraps'],
        ['name_tr' => 'Adana Köfte Dürüm', 'name_en' => 'Adana Meatball Wrap', 'description_tr' => '120 gr ızgara köfte, karamelize soğan, ızgara domates, Babyloon sos, salata ve cips ile servis edilir.', 'description_en' => '120 g grilled meatball, caramelised onion, grilled tomato and Babyloon sauce; served with salad and chips.', 'price' => 530, 'group_tr' => 'Dürümler', 'group_en' => 'Wraps'],
        ['name_tr' => 'Kıbrıs Köfte Dürüm', 'name_en' => 'Cyprus Meatball Wrap', 'description_tr' => '120 gr ızgara köfte, ızgara hellim, patates, ızgara domates, Babyloon sos, salata ve cips ile servis edilir.', 'description_en' => '120 g grilled meatball, grilled halloumi, potato, grilled tomato and Babyloon sauce; served with salad and chips.', 'price' => 540, 'group_tr' => 'Dürümler', 'group_en' => 'Wraps'],
        ['name_tr' => 'Et Fajita Servis', 'name_en' => 'Beef Fajita Platter', 'description_tr' => 'Özenle marine edilmiş dana bonfile, salsa sos ve guaçamole sosu, tortilla ekmeği ile servis edilir.', 'description_en' => 'Carefully marinated beef tenderloin with salsa and guacamole; served with tortillas.', 'price' => 750, 'group_tr' => 'Meksika Mutfağı', 'group_en' => 'Mexican'],
        ['name_tr' => 'Tavuk Fajita Servis', 'name_en' => 'Chicken Fajita Platter', 'description_tr' => 'Özenle marine edilmiş tavuk dilimleri, salsa sos ve guaçamole sosu, tortilla ekmeği ile servis edilir.', 'description_en' => 'Carefully marinated chicken strips with salsa and guacamole; served with tortillas.', 'price' => 700, 'group_tr' => 'Meksika Mutfağı', 'group_en' => 'Mexican'],
        ['name_tr' => 'Fajita Combo Servis', 'name_en' => 'Combo Fajita Platter', 'description_tr' => 'Özenle marine edilmiş dana bonfile ve tavuk dilimleri, salsa sos ve guaçamole sosu, tortilla ekmeği ile servis edilir.', 'description_en' => 'Carefully marinated beef tenderloin and chicken strips with salsa and guacamole; served with tortillas.', 'price' => 770, 'group_tr' => 'Meksika Mutfağı', 'group_en' => 'Mexican'],
        ['name_tr' => 'Tavuk Fajita Dürüm', 'name_en' => 'Chicken Fajita Wrap', 'description_tr' => 'Özenle marine edilmiş tavuk dilimleri, mevsim salatası, cips, tortilla ekmeği içerisinde servis edilir.', 'description_en' => 'Carefully marinated chicken strips, seasonal salad and chips, wrapped in a tortilla.', 'price' => 550, 'group_tr' => 'Meksika Mutfağı', 'group_en' => 'Mexican'],
        ['name_tr' => 'Et Fajita Dürüm', 'name_en' => 'Beef Fajita Wrap', 'description_tr' => 'Özenle marine edilmiş dana bonfile, mevsim salatası, cips, tortilla ekmeği içerisinde servis edilir.', 'description_en' => 'Carefully marinated beef tenderloin, seasonal salad and chips, wrapped in a tortilla.', 'price' => 650, 'group_tr' => 'Meksika Mutfağı', 'group_en' => 'Mexican'],
    ]],
    ['burger', 'Burgerler', 'Burgers', 'Ev yapımı köfte, cips ile', 'Homemade patties, served with fries', 'plate', [
        ['name_tr' => 'Babyloon Double Kasap Burger', 'name_en' => 'Babyloon Double Butcher Burger', 'description_tr' => 'Ev yapımı 320 gr dana antrikot eti, eritilmiş peynir, soğan halkası, cips ile servis edilir.', 'description_en' => 'Homemade 320 g beef entrecôte patty, melted cheese and onion rings; served with chips.', 'price' => 800],
        ['name_tr' => 'Kasap Burger', 'name_en' => 'Butcher Burger', 'description_tr' => 'Ev yapımı 160 gr dana antrikot eti, soğan halkası, cips ile servis edilir.', 'description_en' => 'Homemade 160 g beef entrecôte patty and onion rings; served with chips.', 'price' => 650],
        ['name_tr' => 'Cheese Burger', 'name_en' => 'Cheeseburger', 'description_tr' => 'Ev yapımı 160 gr dana antrikot eti, eritilmiş peynir, soğan halkası, cips ile servis edilir.', 'description_en' => 'Homemade 160 g beef entrecôte patty, melted cheese and onion rings; served with chips.', 'price' => 670],
        ['name_tr' => 'Kumru Burger', 'name_en' => 'Kumru Burger', 'description_tr' => '160 gr dana hamburger eti, ızgara sosis, cheddar peyniri, ızgara domates, kornişon turşu, marul, çıtır soğan halkası, turşu süs biber, Babyloon sos ve cips ile servis edilir.', 'description_en' => '160 g beef patty, grilled sausage, cheddar, grilled tomato, gherkins, lettuce, crispy onion rings, pickled peppers and Babyloon sauce; served with chips.', 'price' => 670],
        ['name_tr' => 'Meksikan Burger', 'name_en' => 'Mexican Burger', 'description_tr' => '160 gr dana hamburger eti, cheddar peyniri, ızgara domates, kornişon turşu, acı biber sos, marul, çıtır soğan halkası, turşu süs biber, Babyloon sos ve cips ile servis edilir.', 'description_en' => '160 g beef patty, cheddar, grilled tomato, gherkins, hot chilli sauce, lettuce, crispy onion rings, pickled peppers and Babyloon sauce; served with chips.', 'price' => 670],
        ['name_tr' => 'Cyprus Burger', 'name_en' => 'Cyprus Burger', 'description_tr' => '160 gr dana hamburger eti, ızgara domates, ızgara hellim, cheddar peyniri, kornişon turşu, marul, çıtır soğan halkası, biber turşusu, özel sos ve cips ile servis edilir.', 'description_en' => '160 g beef patty, grilled tomato, grilled halloumi, cheddar, gherkins, lettuce, crispy onion rings, pickled peppers and special sauce; served with chips.', 'price' => 680],
        ['name_tr' => 'Chef Burger', 'name_en' => 'Chef Burger', 'description_tr' => '160 gr dana hamburger eti, karamelize soğan, ızgara domates, cheddar peyniri, marul, kornişon turşu, çıtır soğan halkası, turşu biber, özel sos ve cips ile servis edilir.', 'description_en' => '160 g beef patty, caramelised onion, grilled tomato, cheddar, lettuce, gherkins, crispy onion rings, pickled peppers and special sauce; served with chips.', 'price' => 680],
    ]],
    ['pizza', 'Pizzalar', 'Pizzas', null, null, 'plate', [
        ['name_tr' => 'Babyloon Pizza', 'name_en' => 'Babyloon Pizza', 'description_tr' => 'Özel pizza sosu, mozzarella peyniri, tavuk eti, kıyma, yeşil biber, zeytin, mantar', 'description_en' => 'Special pizza sauce, mozzarella, chicken, minced beef, green pepper, olives and mushrooms.', 'price' => 760],
        ['name_tr' => 'Chicken Alfredo', 'name_en' => 'Chicken Alfredo Pizza', 'description_tr' => 'Özel pizza sosu, mozzarella peyniri, tavuk eti, yeşil biber, mantar', 'description_en' => 'Special pizza sauce, mozzarella, chicken, green pepper and mushrooms.', 'price' => 740],
        ['name_tr' => 'Meat Pizza', 'name_en' => 'Meat Pizza', 'description_tr' => 'Özel pizza sosu, mozzarella peyniri, kıyma, mantar, yeşil biber.', 'description_en' => 'Special pizza sauce, mozzarella, minced beef, mushrooms and green pepper.', 'price' => 750],
        ['name_tr' => 'Pepperoni Pizza', 'name_en' => 'Pepperoni Pizza', 'description_tr' => 'Özel pizza sosu, mozzarella peyniri, sucuk, sosis, yeşil biber', 'description_en' => 'Special pizza sauce, mozzarella, sucuk, sausage and green pepper.', 'price' => 720],
        ['name_tr' => 'Vegetarian Pizza', 'name_en' => 'Vegetarian Pizza', 'description_tr' => 'Özel pizza sosu, mozzarella peyniri, mısır, mantar, zeytin, yeşil biber, domates', 'description_en' => 'Special pizza sauce, mozzarella, sweetcorn, mushrooms, olives, green pepper and tomato.', 'price' => 700],
        ['name_tr' => 'Quattra Pizza', 'name_en' => 'Quattra Pizza', 'description_tr' => 'Özel pizza sosu, mozzarella peyniri, sucuk, mısır, sosis, yeşil biber, domates, zeytin', 'description_en' => 'Special pizza sauce, mozzarella, sucuk, sweetcorn, sausage, green pepper, tomato and olives.', 'price' => 730],
        ['name_tr' => 'Ton Balıklı Pizza', 'name_en' => 'Tuna Pizza', 'description_tr' => 'Özel pizza sosu, mozzarella peyniri, mısır, yeşil biber, domates, ton balığı', 'description_en' => 'Special pizza sauce, mozzarella, sweetcorn, green pepper, tomato and tuna.', 'price' => 770],
        ['name_tr' => 'Margarita Pizza', 'name_en' => 'Margherita Pizza', 'description_tr' => 'Özel pizza sosu, mozzarella peyniri, domates, fesleğen sosu', 'description_en' => 'Special pizza sauce, mozzarella, tomato and basil sauce.', 'price' => 690],
        ['name_tr' => 'Beef Pizza', 'name_en' => 'Beef Pizza', 'price' => 770],
    ]],
    ['ana', 'Ana Yemekler', 'Mains', 'Tavuk, köfte, makarna', 'Chicken, meatballs, pasta', 'plate', [
        ['name_tr' => 'Izgara Kasap Köfte', 'name_en' => 'Grilled Butcher’s Meatballs', 'description_tr' => '5 adet kasap köfte; mevsim yeşillikleri, turşu ve cips ile servis edilir.', 'description_en' => 'Five butcher’s meatballs; served with seasonal greens, pickles and chips.', 'price' => 750, 'group_tr' => 'Köfte', 'group_en' => 'Meatballs'],
        ['name_tr' => 'Soslu Tavuk Kanat Izgara', 'name_en' => 'Grilled Chicken Wings in Sauce', 'description_tr' => 'Kanat tavuk, mevsim yeşillikleri ve cips ile servis edilir.', 'description_en' => 'Chicken wings; served with seasonal greens and chips.', 'price' => 720, 'group_tr' => 'Tavuk', 'group_en' => 'Chicken'],
        ['name_tr' => 'Tavuk Straganof', 'name_en' => 'Chicken Stroganoff', 'description_tr' => 'Tavuk, mantar, kornişon turşu, hardal soslu krema, mevsim yeşillikleri ve makarna ile servis edilir.', 'description_en' => 'Chicken, mushrooms, gherkins and mustard cream sauce; served with seasonal greens and pasta.', 'price' => 700, 'group_tr' => 'Tavuk', 'group_en' => 'Chicken'],
        ['name_tr' => 'Izgara Tavuk Bonfile', 'name_en' => 'Grilled Chicken Fillet', 'description_tr' => 'Özel Babyloon baharatları ile marine edilmiş tortilla yatağında ızgara tavuk bonfile parçaları; salata ve cips ile servis edilir.', 'description_en' => 'Grilled chicken fillet pieces marinated in special Babyloon spices, on a bed of tortilla; served with salad and chips.', 'price' => 700, 'group_tr' => 'Tavuk', 'group_en' => 'Chicken'],
        ['name_tr' => 'Tex Max Tavuk', 'name_en' => 'Tex-Mex Chicken', 'description_tr' => 'Tavuk, biber, süs biberi, yanında mevsim salatası ve makarna eşliğinde servis edilir.', 'description_en' => 'Chicken, peppers and decorative peppers; served with seasonal salad and pasta.', 'price' => 700, 'group_tr' => 'Tavuk', 'group_en' => 'Chicken'],
        ['name_tr' => 'Tavuk Şinitzel', 'name_en' => 'Chicken Schnitzel', 'description_tr' => 'Limon sos ile marine edilmiş tavuk göğsü, mevsim salatası ve cips ile servis edilir.', 'description_en' => 'Chicken breast marinated in lemon sauce; served with seasonal salad and chips.', 'price' => 700, 'group_tr' => 'Tavuk', 'group_en' => 'Chicken'],
        ['name_tr' => 'Köri Soslu Mantarlı Tavuk', 'name_en' => 'Curry Chicken with Mushrooms', 'description_tr' => 'Tavuk, krema, mantar, mevsim yeşillikleri ve makarna ile servis edilir.', 'description_en' => 'Chicken, cream and mushrooms; served with seasonal greens and pasta.', 'price' => 700, 'group_tr' => 'Tavuk', 'group_en' => 'Chicken'],
        ['name_tr' => 'Bordeaux Soslu Tavuk', 'name_en' => 'Bordeaux Sauce Chicken', 'description_tr' => 'Tavuk, krema, mantar, kaşarlı krema, mevsim yeşillikleri ve makarna ile servis edilir.', 'description_en' => 'Chicken, cream, mushrooms and kashar cheese cream; served with seasonal greens and pasta.', 'price' => 700, 'group_tr' => 'Tavuk', 'group_en' => 'Chicken'],
        ['name_tr' => 'Mantı', 'name_en' => 'Mantı (Turkish Dumplings)', 'price' => 500, 'group_tr' => 'Makarna & Mantı', 'group_en' => 'Pasta & Mantı'],
        ['name_tr' => 'Penne Pasta', 'name_en' => 'Penne Pasta', 'description_tr' => 'Domatesli özel sos, kıyma ve kaşar peyniri ile servis edilir.', 'description_en' => 'Special tomato sauce with minced beef and kashar cheese.', 'price' => 520, 'group_tr' => 'Makarna & Mantı', 'group_en' => 'Pasta & Mantı'],
        ['name_tr' => 'Spagetti Bolognese', 'name_en' => 'Spaghetti Bolognese', 'description_tr' => 'Bolognese sos ve kaşar peyniri ile servis edilir.', 'description_en' => 'Served with Bolognese sauce and kashar cheese.', 'price' => 520, 'group_tr' => 'Makarna & Mantı', 'group_en' => 'Pasta & Mantı'],
        ['name_tr' => 'Köri Soslu Makarna', 'name_en' => 'Curry Penne', 'description_tr' => 'Penne makarna, körili krema ile servis edilir.', 'description_en' => 'Penne pasta in curry cream sauce.', 'price' => 550, 'group_tr' => 'Makarna & Mantı', 'group_en' => 'Pasta & Mantı'],
        ['name_tr' => 'Alfredo Penne Pasta', 'name_en' => 'Penne Alfredo', 'price' => 550, 'group_tr' => 'Makarna & Mantı', 'group_en' => 'Pasta & Mantı'],
    ]],
    ['salata', 'Salatalar', 'Salads', null, null, 'leaf', [
        ['name_tr' => 'Sezar Salata', 'name_en' => 'Caesar Salad', 'description_tr' => 'Mevsim yeşillikleri, ızgara tavuk dilimleri, kıtır ekmek ve sezar sosu ile servis edilir.', 'description_en' => 'Seasonal greens, grilled chicken strips, croutons and Caesar dressing.', 'price' => 530],
        ['name_tr' => 'Izgara Hellim Salata', 'name_en' => 'Grilled Halloumi Salad', 'description_tr' => 'Mevsim yeşillikleri, ızgara hellim dilimleri ve pesto sos ile servis edilir.', 'description_en' => 'Seasonal greens, grilled halloumi slices and pesto.', 'price' => 520],
        ['name_tr' => 'Ton Balıklı Salata', 'name_en' => 'Tuna Salad', 'description_tr' => 'Mevsim yeşillikleri, mısır, ton balığı ve özel sos ile servis edilir.', 'description_en' => 'Seasonal greens, sweetcorn, tuna and special dressing.', 'price' => 550],
        ['name_tr' => 'Beyaz Peynirli Salata', 'name_en' => 'Feta Cheese Salad', 'description_tr' => 'Mevsim yeşillikleri, roka, beyaz peynir ve özel sos ile servis edilir.', 'description_en' => 'Seasonal greens, rocket, feta cheese and special dressing.', 'price' => 520],
    ]],
    ['atistirmalik', 'Tost, Gözleme & Atıştırmalık', 'Toasties, Gözleme & Snacks', 'Tüm tost ve gözleme çeşitlerimiz mevsim salata ve cips ile servis edilir.', 'All toasties and gözleme are served with seasonal salad and fries.', 'plate', [
        ['name_tr' => 'Beyaz Peynirli Tost', 'name_en' => 'Feta Cheese Toastie', 'price' => 380, 'group_tr' => 'Tostlar', 'group_en' => 'Toasties'],
        ['name_tr' => 'Kaşarlı Tost', 'name_en' => 'Cheese Toastie', 'price' => 380, 'group_tr' => 'Tostlar', 'group_en' => 'Toasties'],
        ['name_tr' => 'Hellimli Kaşarlı Tost', 'name_en' => 'Halloumi & Cheese Toastie', 'price' => 385, 'group_tr' => 'Tostlar', 'group_en' => 'Toasties'],
        ['name_tr' => 'Karışık Tost', 'name_en' => 'Mixed Toastie', 'description_tr' => 'Sucuk, Kaşar', 'description_en' => 'Sucuk and kashar cheese.', 'price' => 385, 'group_tr' => 'Tostlar', 'group_en' => 'Toasties'],
        ['name_tr' => 'Yengen Tost', 'name_en' => 'Yengen Toastie', 'description_tr' => 'Sucuk, kaşar, yeşil biber, domates', 'description_en' => 'Sucuk, kashar cheese, green pepper and tomato.', 'price' => 385, 'group_tr' => 'Tostlar', 'group_en' => 'Toasties'],
        ['name_tr' => 'Kaşarlı Gözleme', 'name_en' => 'Cheese Gözleme', 'price' => 435, 'group_tr' => 'Gözlemeler', 'group_en' => 'Gözleme'],
        ['name_tr' => 'Patatesli Gözleme', 'name_en' => 'Potato Gözleme', 'price' => 435, 'group_tr' => 'Gözlemeler', 'group_en' => 'Gözleme'],
        ['name_tr' => 'B.Peynirli Gözleme', 'name_en' => 'Feta Cheese Gözleme', 'price' => 445, 'group_tr' => 'Gözlemeler', 'group_en' => 'Gözleme'],
        ['name_tr' => 'Hellimli Gözleme', 'name_en' => 'Halloumi Gözleme', 'price' => 445, 'group_tr' => 'Gözlemeler', 'group_en' => 'Gözleme'],
        ['name_tr' => 'Kıymalı Gözleme', 'name_en' => 'Minced Beef Gözleme', 'price' => 445, 'group_tr' => 'Gözlemeler', 'group_en' => 'Gözleme'],
        ['name_tr' => 'Sosisli - Kaşarlı Gözleme', 'name_en' => 'Sausage & Cheese Gözleme', 'price' => 445, 'group_tr' => 'Gözlemeler', 'group_en' => 'Gözleme'],
        ['name_tr' => 'Kıymalı - Kaşarlı Gözleme', 'name_en' => 'Minced Beef & Cheese Gözleme', 'price' => 455, 'group_tr' => 'Gözlemeler', 'group_en' => 'Gözleme'],
        ['name_tr' => 'Karışık Gözleme', 'name_en' => 'Mixed Gözleme', 'price' => 455, 'group_tr' => 'Gözlemeler', 'group_en' => 'Gözleme'],
        ['name_tr' => 'Sosis Tabağı', 'name_en' => 'Sausage Plate', 'price' => 450, 'group_tr' => 'Atıştırmalıklar', 'group_en' => 'Snacks'],
        ['name_tr' => 'Soğan Halkası', 'name_en' => 'Onion Rings', 'price' => 450, 'group_tr' => 'Atıştırmalıklar', 'group_en' => 'Snacks'],
        ['name_tr' => 'Nugget Tabağı', 'name_en' => 'Nugget Plate', 'price' => 480, 'group_tr' => 'Atıştırmalıklar', 'group_en' => 'Snacks'],
        ['name_tr' => 'Patates Tava', 'name_en' => 'French Fries', 'price' => 300, 'group_tr' => 'Atıştırmalıklar', 'group_en' => 'Snacks'],
        ['name_tr' => 'Kaşarlı Patates Tava', 'name_en' => 'Cheesy Fries', 'price' => 330, 'group_tr' => 'Atıştırmalıklar', 'group_en' => 'Snacks'],
        ['name_tr' => 'Ortaya Karışık', 'name_en' => 'Mixed Sharing Platter', 'description_tr' => 'Cips, Tavuk, Soğan Halkası, Sosis, Sigara Böreği, Köfte', 'description_en' => 'Chips, chicken, onion rings, sausage, cheese rolls (sigara böreği) and meatballs.', 'price' => 520, 'group_tr' => 'Atıştırmalıklar', 'group_en' => 'Snacks'],
        ['name_tr' => 'Ton Balıklı Sandviç', 'name_en' => 'Tuna Sandwich', 'description_tr' => 'Yarım ekmek arasında tüm ton balığı 140 gr, domates, soğan, kornişon turşu, marul, acı biber turşusu ve cips ile servis edilir.', 'description_en' => 'Half a loaf filled with 140 g whole tuna, tomato, onion, gherkins, lettuce and pickled chilli; served with chips.', 'price' => 490, 'group_tr' => 'Sandviç', 'group_en' => 'Sandwich'],
    ]],
    ['kahvalti', 'Kahvaltı', 'Breakfast', null, null, 'cup', [
        ['name_tr' => 'Serpme Kahvaltı', 'name_en' => 'Turkish Breakfast Spread', 'description_tr' => 'Menemen, kıymalı yumurta, bal, kaymak, kaşar peyniri, hellim ızgara, beyaz peynir, çilek reçeli, kayısı reçeli, salam, sucuk, sosis, siyah zeytin, yeşil zeytin, domates, salatalık, patates kızartması, meyve suyu, kaşarlı tost, sınırsız çay.', 'description_en' => 'Menemen, eggs with minced beef, honey, clotted cream, kashar cheese, grilled halloumi, feta, strawberry jam, apricot jam, salami, sucuk, sausage, black and green olives, tomato, cucumber, chips, fruit juice, cheese toastie and unlimited tea.', 'price' => 1650, 'size1_tr' => 'İki Kişilik', 'size1_en' => 'For two', 'group_tr' => 'Kahvaltılar', 'group_en' => 'Breakfasts'],
        ['name_tr' => 'Kahvaltı Tabağı', 'name_en' => 'Breakfast Plate', 'description_tr' => 'Yumurta, beyaz peynir, hellim, kaşar peyniri, salam, siyah zeytin, yeşil zeytin, tereyağ, bal, kaymak, domates, salatalık, reçel, limonata, sınırsız çay.', 'description_en' => 'Egg, feta, halloumi, kashar cheese, salami, black and green olives, butter, honey, clotted cream, tomato, cucumber, jam, lemonade and unlimited tea.', 'price' => 700, 'group_tr' => 'Kahvaltılar', 'group_en' => 'Breakfasts'],
        ['name_tr' => 'Sıcak Kahvaltı', 'name_en' => 'Hot Breakfast', 'description_tr' => 'Menemen, yumurta, patates kızartması, hellim ızgara, sosis, domates, salatalık, kaşarlı tost, limonata, sınırsız çay.', 'description_en' => 'Menemen, egg, chips, grilled halloumi, sausage, tomato, cucumber, cheese toastie, lemonade and unlimited tea.', 'price' => 750, 'group_tr' => 'Kahvaltılar', 'group_en' => 'Breakfasts'],
        ['name_tr' => 'Hellim Izgara (4 dilim)', 'name_en' => 'Grilled Halloumi (4 slices)', 'price' => 300, 'group_tr' => 'Kahvaltılar', 'group_en' => 'Breakfasts'],
        ['name_tr' => 'Bal + Kaymak', 'name_en' => 'Honey & Clotted Cream', 'price' => 250, 'group_tr' => 'Kahvaltılar', 'group_en' => 'Breakfasts'],
        ['name_tr' => 'Sade Yumurta', 'name_en' => 'Fried Eggs', 'price' => 220, 'group_tr' => 'Sahanda Yumurta', 'group_en' => 'Fried Eggs'],
        ['name_tr' => 'Sucuklu Yumurta', 'name_en' => 'Eggs with Sucuk', 'price' => 250, 'group_tr' => 'Sahanda Yumurta', 'group_en' => 'Fried Eggs'],
        ['name_tr' => 'Sosisli Yumurta', 'name_en' => 'Eggs with Sausage', 'price' => 250, 'group_tr' => 'Sahanda Yumurta', 'group_en' => 'Fried Eggs'],
        ['name_tr' => 'Beyaz Peynirli Yumurta', 'name_en' => 'Eggs with Feta', 'price' => 250, 'group_tr' => 'Sahanda Yumurta', 'group_en' => 'Fried Eggs'],
        ['name_tr' => 'Sade Menemen', 'name_en' => 'Plain Menemen', 'price' => 390, 'group_tr' => 'Menemen', 'group_en' => 'Menemen'],
        ['name_tr' => 'Kaşarlı Menemen', 'name_en' => 'Menemen with Cheese', 'price' => 420, 'group_tr' => 'Menemen', 'group_en' => 'Menemen'],
        ['name_tr' => 'Beyaz Peynirli Menemen', 'name_en' => 'Menemen with Feta', 'price' => 420, 'group_tr' => 'Menemen', 'group_en' => 'Menemen'],
        ['name_tr' => 'Karışık Menemen', 'name_en' => 'Mixed Menemen', 'price' => 430, 'group_tr' => 'Menemen', 'group_en' => 'Menemen'],
        ['name_tr' => 'Sade Omlet', 'name_en' => 'Plain Omelette', 'price' => 390, 'group_tr' => 'Omlet', 'group_en' => 'Omelettes'],
        ['name_tr' => 'Kaşarlı Omlet', 'name_en' => 'Cheese Omelette', 'price' => 405, 'group_tr' => 'Omlet', 'group_en' => 'Omelettes'],
        ['name_tr' => 'Sosisli Omlet', 'name_en' => 'Sausage Omelette', 'price' => 405, 'group_tr' => 'Omlet', 'group_en' => 'Omelettes'],
        ['name_tr' => 'Kaşarlı Sucuklu Omlet', 'name_en' => 'Cheese & Sucuk Omelette', 'price' => 410, 'group_tr' => 'Omlet', 'group_en' => 'Omelettes'],
        ['name_tr' => 'Kaşarlı Sosisli Omlet', 'name_en' => 'Cheese & Sausage Omelette', 'price' => 410, 'group_tr' => 'Omlet', 'group_en' => 'Omelettes'],
    ]],
    ['tatli', 'Tatlılar', 'Desserts', 'İlave kaymak veya dondurma: 40 ₺', 'Extra clotted cream or ice cream: 40 ₺', 'cake', [
        ['name_tr' => 'Sütlaç', 'name_en' => 'Rice Pudding', 'price' => 280, 'group_tr' => 'Sütlü Tatlılar', 'group_en' => 'Milk Desserts'],
        ['name_tr' => 'Kazandibi', 'name_en' => 'Kazandibi (Caramelised Milk Pudding)', 'price' => 280, 'group_tr' => 'Sütlü Tatlılar', 'group_en' => 'Milk Desserts'],
        ['name_tr' => 'Trileçe', 'name_en' => 'Trileçe (Three-Milk Cake)', 'price' => 330, 'group_tr' => 'Sütlü Tatlılar', 'group_en' => 'Milk Desserts'],
        ['name_tr' => 'Çikolatalı Sufle', 'name_en' => 'Chocolate Soufflé', 'price' => 420, 'group_tr' => 'Sütlü Tatlılar', 'group_en' => 'Milk Desserts'],
        ['name_tr' => 'Dondurmalı Sufle', 'name_en' => 'Chocolate Soufflé with Ice Cream', 'price' => 450, 'group_tr' => 'Sütlü Tatlılar', 'group_en' => 'Milk Desserts'],
        ['name_tr' => 'Künefe', 'name_en' => 'Künefe', 'price' => 420, 'group_tr' => 'Şerbetli Tatlılar', 'group_en' => 'Syrup Desserts'],
        ['name_tr' => 'Dondurmalı Künefe', 'name_en' => 'Künefe with Ice Cream', 'price' => 450, 'group_tr' => 'Şerbetli Tatlılar', 'group_en' => 'Syrup Desserts'],
        ['name_tr' => 'Kaymaklı Künefe', 'name_en' => 'Künefe with Clotted Cream', 'price' => 450, 'group_tr' => 'Şerbetli Tatlılar', 'group_en' => 'Syrup Desserts'],
        ['name_tr' => 'Havuç Dilim Baklava', 'name_en' => 'Carrot-Slice Baklava', 'price' => 350, 'group_tr' => 'Şerbetli Tatlılar', 'group_en' => 'Syrup Desserts'],
        ['name_tr' => 'Karamelli Trileçe', 'name_en' => 'Caramel Trileçe', 'price' => 330, 'group_tr' => 'Pastalar', 'group_en' => 'Cakes'],
        ['name_tr' => 'Mozaik Pasta', 'name_en' => 'Mosaic Cake', 'price' => 350, 'group_tr' => 'Pastalar', 'group_en' => 'Cakes'],
        ['name_tr' => 'Tiramisu', 'name_en' => 'Tiramisu', 'price' => 395, 'group_tr' => 'Pastalar', 'group_en' => 'Cakes'],
        ['name_tr' => 'Limonlu Cheesecake', 'name_en' => 'Lemon Cheesecake', 'price' => 350, 'group_tr' => 'Pastalar', 'group_en' => 'Cakes'],
        ['name_tr' => 'Vanilyalı Krep Pasta', 'name_en' => 'Vanilla Crêpe Cake', 'price' => 395, 'group_tr' => 'Pastalar', 'group_en' => 'Cakes'],
        ['name_tr' => 'Limonlu Molten Kek', 'name_en' => 'Lemon Molten Cake', 'price' => 395, 'group_tr' => 'Pastalar', 'group_en' => 'Cakes'],
        ['name_tr' => 'Karamelize Bisküvili Pasta', 'name_en' => 'Caramelised Biscuit Cake', 'price' => 395, 'group_tr' => 'Pastalar', 'group_en' => 'Cakes'],
        ['name_tr' => 'Fıstık Rüyası', 'name_en' => 'Pistachio Dream', 'price' => 395, 'group_tr' => 'Pastalar', 'group_en' => 'Cakes'],
        ['name_tr' => 'Kremalı Havuçlu Kek', 'name_en' => 'Carrot Cake with Cream', 'price' => 395, 'group_tr' => 'Pastalar', 'group_en' => 'Cakes'],
        ['name_tr' => 'Kahveli Krep Pasta', 'name_en' => 'Coffee Crêpe Cake', 'price' => 395, 'group_tr' => 'Pastalar', 'group_en' => 'Cakes'],
        ['name_tr' => 'Profiterollü Pasta', 'name_en' => 'Profiterole Cake', 'price' => 350, 'group_tr' => 'Pastalar', 'group_en' => 'Cakes'],
        ['name_tr' => 'Brownie', 'name_en' => 'Brownie', 'price' => 350, 'group_tr' => 'Pastalar', 'group_en' => 'Cakes'],
        ['name_tr' => 'Dondurmalı Brownie', 'name_en' => 'Brownie with Ice Cream', 'price' => 380, 'group_tr' => 'Pastalar', 'group_en' => 'Cakes'],
        ['name_tr' => 'Meyveli Magnolya', 'name_en' => 'Fruit Magnolia', 'price' => 350, 'group_tr' => 'Pastalar', 'group_en' => 'Cakes'],
        ['name_tr' => 'Muzlu Magnolya', 'name_en' => 'Banana Magnolia', 'price' => 350, 'group_tr' => 'Pastalar', 'group_en' => 'Cakes'],
        ['name_tr' => 'Dondurmalı Mozaik', 'name_en' => 'Mosaic Cake with Ice Cream', 'price' => 380, 'group_tr' => 'Pastalar', 'group_en' => 'Cakes'],
        ['name_tr' => 'Sade Waffle (meyvesiz)', 'name_en' => 'Plain Waffle (no fruit)', 'price' => 400, 'group_tr' => 'Pastalar', 'group_en' => 'Cakes'],
        ['name_tr' => 'Meyveli Waffle', 'name_en' => 'Fruit Waffle', 'price' => 450, 'group_tr' => 'Pastalar', 'group_en' => 'Cakes'],
        ['name_tr' => 'Dondurmalı Waffle', 'name_en' => 'Waffle with Ice Cream', 'price' => 500, 'group_tr' => 'Pastalar', 'group_en' => 'Cakes'],
        ['name_tr' => 'Delvis', 'name_en' => 'Delvis', 'price' => 350, 'group_tr' => 'Pastalar', 'group_en' => 'Cakes'],
        ['name_tr' => 'Meyve Tabağı', 'name_en' => 'Fruit Platter', 'price' => 500, 'group_tr' => 'Pastalar', 'group_en' => 'Cakes'],
        ['name_tr' => 'Çerez Tabağı', 'name_en' => 'Mixed Nuts Platter', 'price' => 350, 'group_tr' => 'Pastalar', 'group_en' => 'Cakes'],
        ['name_tr' => 'Dondurma', 'name_en' => 'Ice Cream', 'description_tr' => 'Sade, çikolata, muz, çilek, karamel, fıstık, limon, karadut, kavun. Bir porsiyonda 4 top vardır.', 'description_en' => 'Vanilla, chocolate, banana, strawberry, caramel, pistachio, lemon, black mulberry, melon. One portion is 4 scoops.', 'price' => 120, 'price2' => 480, 'size1_tr' => 'Top', 'size1_en' => 'Scoop', 'size2_tr' => 'Porsiyon', 'size2_en' => 'Portion', 'group_tr' => 'Dondurmalar', 'group_en' => 'Ice Cream'],
        ['name_tr' => 'Dondurmalı Çilek Kasesi', 'name_en' => 'Strawberry Ice Cream Bowl', 'description_tr' => '3 top dondurma, çilek, kremşanti, çilek sos', 'description_en' => '3 scoops of ice cream, strawberries, whipped cream and strawberry sauce.', 'price' => 480, 'group_tr' => 'Dondurmalar', 'group_en' => 'Ice Cream'],
        ['name_tr' => 'Dondurmalı Muz Kasesi', 'name_en' => 'Banana Ice Cream Bowl', 'description_tr' => '3 top dondurma, muz dilimleri, kremşanti, çikolata sos', 'description_en' => '3 scoops of ice cream, banana slices, whipped cream and chocolate sauce.', 'price' => 480, 'group_tr' => 'Dondurmalar', 'group_en' => 'Ice Cream'],
        ['name_tr' => 'Dondurmalı Akdeniz Kasesi', 'name_en' => 'Mediterranean Ice Cream Bowl', 'description_tr' => '3 top dondurma, muz ve çilek dilimleri, kremşanti, çikolata sos', 'description_en' => '3 scoops of ice cream, banana and strawberry slices, whipped cream and chocolate sauce.', 'price' => 480, 'group_tr' => 'Dondurmalar', 'group_en' => 'Ice Cream'],
        ['name_tr' => 'Banana Split', 'name_en' => 'Banana Split', 'price' => 400, 'group_tr' => 'Dondurmalar', 'group_en' => 'Ice Cream'],
        ['name_tr' => 'Dondurmalı Meyve Bahçesi', 'name_en' => 'Ice Cream Fruit Garden', 'description_tr' => 'İsteğe göre 3 top dondurma; kivi, muz, çilek, portakal ve elma ile kremşanti, çilek ve çikolata sos.', 'description_en' => '3 scoops of ice cream of your choice with kiwi, banana, strawberry, orange and apple, whipped cream, strawberry and chocolate sauce.', 'price' => 500, 'group_tr' => 'Dondurmalar', 'group_en' => 'Ice Cream'],
    ]],
    ['soguk', 'Soğuk İçecekler', 'Cold Drinks', null, null, 'ice', [
        ['name_tr' => 'Strawberry Chillers', 'name_en' => 'Strawberry Chillers', 'price' => 260, 'group_tr' => 'Fruit Chillers', 'group_en' => 'Fruit Chillers'],
        ['name_tr' => 'Lemon Chillers', 'name_en' => 'Lemon Chillers', 'price' => 260, 'group_tr' => 'Fruit Chillers', 'group_en' => 'Fruit Chillers'],
        ['name_tr' => 'Melon Chillers', 'name_en' => 'Melon Chillers', 'price' => 260, 'group_tr' => 'Fruit Chillers', 'group_en' => 'Fruit Chillers'],
        ['name_tr' => 'Black Berry Chillers', 'name_en' => 'Blackberry Chillers', 'price' => 260, 'group_tr' => 'Fruit Chillers', 'group_en' => 'Fruit Chillers'],
        ['name_tr' => 'Çikolatalı Milkshake', 'name_en' => 'Chocolate Milkshake', 'price' => 270, 'group_tr' => 'Milkshake & Smoothie', 'group_en' => 'Milkshake & Smoothie'],
        ['name_tr' => 'Muzlu Milkshake', 'name_en' => 'Banana Milkshake', 'price' => 270, 'group_tr' => 'Milkshake & Smoothie', 'group_en' => 'Milkshake & Smoothie'],
        ['name_tr' => 'Çilekli Milkshake', 'name_en' => 'Strawberry Milkshake', 'price' => 270, 'group_tr' => 'Milkshake & Smoothie', 'group_en' => 'Milkshake & Smoothie'],
        ['name_tr' => 'Vanilyalı Milkshake', 'name_en' => 'Vanilla Milkshake', 'price' => 270, 'group_tr' => 'Milkshake & Smoothie', 'group_en' => 'Milkshake & Smoothie'],
        ['name_tr' => 'Karamelli Milkshake', 'name_en' => 'Caramel Milkshake', 'price' => 270, 'group_tr' => 'Milkshake & Smoothie', 'group_en' => 'Milkshake & Smoothie'],
        ['name_tr' => 'Çilekli Smoothie', 'name_en' => 'Strawberry Smoothie', 'price' => 280, 'group_tr' => 'Milkshake & Smoothie', 'group_en' => 'Milkshake & Smoothie'],
        ['name_tr' => 'Karadut Smoothie', 'name_en' => 'Black Mulberry Smoothie', 'price' => 280, 'group_tr' => 'Milkshake & Smoothie', 'group_en' => 'Milkshake & Smoothie'],
        ['name_tr' => 'Karamel Smoothie', 'name_en' => 'Caramel Smoothie', 'price' => 280, 'group_tr' => 'Milkshake & Smoothie', 'group_en' => 'Milkshake & Smoothie'],
        ['name_tr' => 'Limonatalı Bubble', 'name_en' => 'Lemonade Bubble Tea', 'price' => 270, 'group_tr' => 'Bubble Tea', 'group_en' => 'Bubble Tea'],
        ['name_tr' => 'Portakallı Bubble', 'name_en' => 'Orange Bubble Tea', 'price' => 280, 'group_tr' => 'Bubble Tea', 'group_en' => 'Bubble Tea'],
        ['name_tr' => 'Latte Bubble', 'name_en' => 'Latte Bubble Tea', 'price' => 310, 'group_tr' => 'Bubble Tea', 'group_en' => 'Bubble Tea'],
        ['name_tr' => 'Milkshake Bubble', 'name_en' => 'Milkshake Bubble Tea', 'price' => 320, 'group_tr' => 'Bubble Tea', 'group_en' => 'Bubble Tea'],
        ['name_tr' => 'Enerji İçecekli Bubble', 'name_en' => 'Energy Drink Bubble Tea', 'price' => 260, 'group_tr' => 'Bubble Tea', 'group_en' => 'Bubble Tea'],
        ['name_tr' => 'Coca Cola', 'name_en' => 'Coca-Cola', 'price' => 115, 'group_tr' => 'Meşrubat', 'group_en' => 'Soft Drinks'],
        ['name_tr' => 'Coca Cola Zero', 'name_en' => 'Coca-Cola Zero', 'price' => 115, 'group_tr' => 'Meşrubat', 'group_en' => 'Soft Drinks'],
        ['name_tr' => 'Fanta', 'name_en' => 'Fanta', 'price' => 115, 'group_tr' => 'Meşrubat', 'group_en' => 'Soft Drinks'],
        ['name_tr' => 'Sprite', 'name_en' => 'Sprite', 'price' => 115, 'group_tr' => 'Meşrubat', 'group_en' => 'Soft Drinks'],
        ['name_tr' => 'Cappy', 'name_en' => 'Cappy Juice', 'price' => 115, 'group_tr' => 'Meşrubat', 'group_en' => 'Soft Drinks'],
        ['name_tr' => 'Fuse Tea', 'name_en' => 'Fuse Tea', 'price' => 115, 'group_tr' => 'Meşrubat', 'group_en' => 'Soft Drinks'],
        ['name_tr' => 'Soda', 'name_en' => 'Sparkling Water', 'price' => 115, 'group_tr' => 'Meşrubat', 'group_en' => 'Soft Drinks'],
        ['name_tr' => 'Meyveli Soda', 'name_en' => 'Flavoured Sparkling Water', 'price' => 115, 'group_tr' => 'Meşrubat', 'group_en' => 'Soft Drinks'],
        ['name_tr' => 'İtalyan Soda', 'name_en' => 'Italian Soda', 'price' => 220, 'group_tr' => 'Meşrubat', 'group_en' => 'Soft Drinks'],
        ['name_tr' => 'İtalyan Soda Çilekli', 'name_en' => 'Italian Soda — Strawberry', 'price' => 220, 'group_tr' => 'Meşrubat', 'group_en' => 'Soft Drinks'],
        ['name_tr' => 'İtalyan Soda Kavunlu', 'name_en' => 'Italian Soda — Melon', 'price' => 220, 'group_tr' => 'Meşrubat', 'group_en' => 'Soft Drinks'],
        ['name_tr' => 'İtalyan Soda Karpuzlu', 'name_en' => 'Italian Soda — Watermelon', 'price' => 220, 'group_tr' => 'Meşrubat', 'group_en' => 'Soft Drinks'],
        ['name_tr' => 'İtalyan Soda Karadutlu', 'name_en' => 'Italian Soda — Black Mulberry', 'price' => 220, 'group_tr' => 'Meşrubat', 'group_en' => 'Soft Drinks'],
        ['name_tr' => 'İtalyan Soda Mavi Melek', 'name_en' => 'Italian Soda — Blue Angel', 'price' => 220, 'group_tr' => 'Meşrubat', 'group_en' => 'Soft Drinks'],
        ['name_tr' => 'Küçük Su', 'name_en' => 'Small Water', 'price' => 70, 'group_tr' => 'Meşrubat', 'group_en' => 'Soft Drinks'],
        ['name_tr' => 'Büyük Su', 'name_en' => 'Large Water', 'price' => 140, 'group_tr' => 'Meşrubat', 'group_en' => 'Soft Drinks'],
        ['name_tr' => 'Ballı Muzlu Süt', 'name_en' => 'Honey Banana Milk', 'price' => 260, 'group_tr' => 'Meşrubat', 'group_en' => 'Soft Drinks'],
        ['name_tr' => 'Limonata', 'name_en' => 'Lemonade', 'price' => 210, 'group_tr' => 'Meşrubat', 'group_en' => 'Soft Drinks'],
        ['name_tr' => 'Çilekli Limonata', 'name_en' => 'Strawberry Lemonade', 'price' => 210, 'group_tr' => 'Meşrubat', 'group_en' => 'Soft Drinks'],
        ['name_tr' => 'Red Bull', 'name_en' => 'Red Bull', 'price' => 210, 'group_tr' => 'Meşrubat', 'group_en' => 'Soft Drinks'],
        ['name_tr' => 'Meksikan Red Bull', 'name_en' => 'Mexican Red Bull', 'price' => 230, 'group_tr' => 'Meşrubat', 'group_en' => 'Soft Drinks'],
        ['name_tr' => 'Çorcil', 'name_en' => 'Churchill (Lemon Soda)', 'price' => 140, 'group_tr' => 'Meşrubat', 'group_en' => 'Soft Drinks'],
        ['name_tr' => 'Taze Portakal Suyu', 'name_en' => 'Fresh Orange Juice', 'price' => 230, 'group_tr' => 'Meşrubat', 'group_en' => 'Soft Drinks'],
        ['name_tr' => 'Ayran', 'name_en' => 'Ayran (Yoghurt Drink)', 'price' => 100, 'group_tr' => 'Meşrubat', 'group_en' => 'Soft Drinks'],
        ['name_tr' => 'Strawberry Iced Chocolate', 'name_en' => 'Strawberry Iced Chocolate', 'price' => 250, 'group_tr' => 'Babyloon Karışımlar', 'group_en' => 'Babyloon Blends'],
        ['name_tr' => 'Karamel Iced Chocolate', 'name_en' => 'Caramel Iced Chocolate', 'price' => 250, 'group_tr' => 'Babyloon Karışımlar', 'group_en' => 'Babyloon Blends'],
        ['name_tr' => 'Coconut Iced Chocolate', 'name_en' => 'Coconut Iced Chocolate', 'price' => 250, 'group_tr' => 'Babyloon Karışımlar', 'group_en' => 'Babyloon Blends'],
        ['name_tr' => 'Cookie\'s Iced Chocolate', 'name_en' => 'Cookie Iced Chocolate', 'price' => 250, 'group_tr' => 'Babyloon Karışımlar', 'group_en' => 'Babyloon Blends'],
        ['name_tr' => 'Orjinal Iced Chocolate', 'name_en' => 'Original Iced Chocolate', 'price' => 250, 'group_tr' => 'Babyloon Karışımlar', 'group_en' => 'Babyloon Blends'],
    ]],
    ['kahve', 'Kahve & Sıcak İçecekler', 'Coffee & Hot Drinks', null, null, 'cup', [
        ['name_tr' => 'Iced Latte', 'name_en' => 'Iced Latte', 'price' => 260, 'group_tr' => 'Soğuk Kahveler', 'group_en' => 'Iced Coffees'],
        ['name_tr' => 'Iced Vanilyalı Latte', 'name_en' => 'Iced Vanilla Latte', 'price' => 260, 'group_tr' => 'Soğuk Kahveler', 'group_en' => 'Iced Coffees'],
        ['name_tr' => 'Iced Karamelli Latte', 'name_en' => 'Iced Caramel Latte', 'price' => 260, 'group_tr' => 'Soğuk Kahveler', 'group_en' => 'Iced Coffees'],
        ['name_tr' => 'Iced Mocha', 'name_en' => 'Iced Mocha', 'price' => 260, 'group_tr' => 'Soğuk Kahveler', 'group_en' => 'Iced Coffees'],
        ['name_tr' => 'Iced Karamel Mocha', 'name_en' => 'Iced Caramel Mocha', 'price' => 260, 'group_tr' => 'Soğuk Kahveler', 'group_en' => 'Iced Coffees'],
        ['name_tr' => 'Iced Americano', 'name_en' => 'Iced Americano', 'price' => 260, 'group_tr' => 'Soğuk Kahveler', 'group_en' => 'Iced Coffees'],
        ['name_tr' => 'Iced Cappuccino', 'name_en' => 'Iced Cappuccino', 'price' => 260, 'group_tr' => 'Soğuk Kahveler', 'group_en' => 'Iced Coffees'],
        ['name_tr' => 'Iced Nescafe', 'name_en' => 'Iced Nescafé', 'price' => 260, 'group_tr' => 'Soğuk Kahveler', 'group_en' => 'Iced Coffees'],
        ['name_tr' => 'Iced Frappe Latte', 'name_en' => 'Iced Frappé Latte', 'price' => 260, 'group_tr' => 'Soğuk Kahveler', 'group_en' => 'Iced Coffees'],
        ['name_tr' => 'Iced Cookie\'s Frappe Latte', 'name_en' => 'Iced Cookie Frappé Latte', 'price' => 260, 'group_tr' => 'Soğuk Kahveler', 'group_en' => 'Iced Coffees'],
        ['name_tr' => 'Frappuccino', 'name_en' => 'Frappuccino', 'price' => 260, 'group_tr' => 'Soğuk Kahveler', 'group_en' => 'Iced Coffees'],
        ['name_tr' => 'Affogato', 'name_en' => 'Affogato', 'price' => 260, 'group_tr' => 'Soğuk Kahveler', 'group_en' => 'Iced Coffees'],
        ['name_tr' => 'Kowa Mint', 'name_en' => 'Kowa Mint', 'price' => 260, 'group_tr' => 'Soğuk Kahveler', 'group_en' => 'Iced Coffees'],
        ['name_tr' => 'Choco - Coco', 'name_en' => 'Choco-Coco', 'price' => 260, 'group_tr' => 'Soğuk Kahveler', 'group_en' => 'Iced Coffees'],
        ['name_tr' => 'Demleme Çay Cam Bardak', 'name_en' => 'Brewed Tea (Glass)', 'price' => 80, 'group_tr' => 'Sıcak İçecekler', 'group_en' => 'Hot Drinks'],
        ['name_tr' => 'Demleme Çay Fincan', 'name_en' => 'Brewed Tea (Cup)', 'price' => 140, 'group_tr' => 'Sıcak İçecekler', 'group_en' => 'Hot Drinks'],
        ['name_tr' => 'Lipton Bitki Çayları', 'name_en' => 'Lipton Herbal Teas', 'price' => 140, 'group_tr' => 'Sıcak İçecekler', 'group_en' => 'Hot Drinks'],
        ['name_tr' => 'Kivi Çayı', 'name_en' => 'Kiwi Tea', 'price' => 95, 'group_tr' => 'Sıcak İçecekler', 'group_en' => 'Hot Drinks'],
        ['name_tr' => 'Muz Çayı', 'name_en' => 'Banana Tea', 'price' => 95, 'group_tr' => 'Sıcak İçecekler', 'group_en' => 'Hot Drinks'],
        ['name_tr' => 'Türk Kahvesi', 'name_en' => 'Turkish Coffee', 'price' => 135, 'group_tr' => 'Sıcak İçecekler', 'group_en' => 'Hot Drinks'],
        ['name_tr' => 'Double Türk Kahvesi', 'name_en' => 'Double Turkish Coffee', 'price' => 170, 'group_tr' => 'Sıcak İçecekler', 'group_en' => 'Hot Drinks'],
        ['name_tr' => 'Con Türk Kahvesi', 'name_en' => 'Con Turkish Coffee', 'price' => 135, 'group_tr' => 'Sıcak İçecekler', 'group_en' => 'Hot Drinks'],
        ['name_tr' => 'Oza Türk Kahvesi', 'name_en' => 'Oza Turkish Coffee', 'price' => 135, 'group_tr' => 'Sıcak İçecekler', 'group_en' => 'Hot Drinks'],
        ['name_tr' => 'Damla Sakızlı Türk Kahvesi', 'name_en' => 'Mastic Turkish Coffee', 'price' => 135, 'group_tr' => 'Sıcak İçecekler', 'group_en' => 'Hot Drinks'],
        ['name_tr' => 'Sütlü Türk Kahvesi', 'name_en' => 'Turkish Coffee with Milk', 'price' => 160, 'group_tr' => 'Sıcak İçecekler', 'group_en' => 'Hot Drinks'],
        ['name_tr' => 'Double Espresso', 'name_en' => 'Double Espresso', 'price' => 170, 'group_tr' => 'Sıcak İçecekler', 'group_en' => 'Hot Drinks'],
        ['name_tr' => 'Espresso Macchiato', 'name_en' => 'Espresso Macchiato', 'price' => 250, 'group_tr' => 'Sıcak İçecekler', 'group_en' => 'Hot Drinks'],
        ['name_tr' => 'Sütlü Nescafe', 'name_en' => 'Nescafé with Milk', 'price' => 240, 'group_tr' => 'Sıcak İçecekler', 'group_en' => 'Hot Drinks'],
        ['name_tr' => 'Sade Nescafe', 'name_en' => 'Black Nescafé', 'price' => 200, 'group_tr' => 'Sıcak İçecekler', 'group_en' => 'Hot Drinks'],
        ['name_tr' => 'Filtre Kahve', 'name_en' => 'Filter Coffee', 'price' => 220, 'group_tr' => 'Sıcak İçecekler', 'group_en' => 'Hot Drinks'],
        ['name_tr' => 'Americano', 'name_en' => 'Americano', 'price' => 240, 'group_tr' => 'Sıcak İçecekler', 'group_en' => 'Hot Drinks'],
        ['name_tr' => 'Cafe Latte', 'name_en' => 'Caffè Latte', 'price' => 240, 'group_tr' => 'Sıcak İçecekler', 'group_en' => 'Hot Drinks'],
        ['name_tr' => 'Karamelli Latte', 'name_en' => 'Caramel Latte', 'price' => 240, 'group_tr' => 'Sıcak İçecekler', 'group_en' => 'Hot Drinks'],
        ['name_tr' => 'Vanilyalı Latte', 'name_en' => 'Vanilla Latte', 'price' => 240, 'group_tr' => 'Sıcak İçecekler', 'group_en' => 'Hot Drinks'],
        ['name_tr' => 'Chai Tea Latte', 'name_en' => 'Chai Tea Latte', 'price' => 240, 'group_tr' => 'Sıcak İçecekler', 'group_en' => 'Hot Drinks'],
        ['name_tr' => 'Sıcak Çikolata', 'name_en' => 'Hot Chocolate', 'price' => 240, 'group_tr' => 'Sıcak İçecekler', 'group_en' => 'Hot Drinks'],
        ['name_tr' => 'Karamelli Sıcak Çikolata', 'name_en' => 'Caramel Hot Chocolate', 'price' => 240, 'group_tr' => 'Sıcak İçecekler', 'group_en' => 'Hot Drinks'],
        ['name_tr' => 'Cafe Mocha', 'name_en' => 'Caffè Mocha', 'price' => 240, 'group_tr' => 'Sıcak İçecekler', 'group_en' => 'Hot Drinks'],
        ['name_tr' => 'Karamelli Cafe Mocha', 'name_en' => 'Caramel Caffè Mocha', 'price' => 240, 'group_tr' => 'Sıcak İçecekler', 'group_en' => 'Hot Drinks'],
        ['name_tr' => 'Nutella Mocha', 'name_en' => 'Nutella Mocha', 'price' => 250, 'group_tr' => 'Sıcak İçecekler', 'group_en' => 'Hot Drinks'],
        ['name_tr' => 'White Chocolate Mocha', 'name_en' => 'White Chocolate Mocha', 'price' => 240, 'group_tr' => 'Sıcak İçecekler', 'group_en' => 'Hot Drinks'],
        ['name_tr' => 'Sahlep', 'name_en' => 'Salep', 'price' => 240, 'group_tr' => 'Sıcak İçecekler', 'group_en' => 'Hot Drinks'],
        ['name_tr' => 'Ballı Süt', 'name_en' => 'Hot Milk with Honey', 'price' => 240, 'group_tr' => 'Sıcak İçecekler', 'group_en' => 'Hot Drinks'],
        ['name_tr' => 'Süt', 'name_en' => 'Hot Milk', 'price' => 200, 'group_tr' => 'Sıcak İçecekler', 'group_en' => 'Hot Drinks'],
        ['name_tr' => 'Süvari Kahve', 'name_en' => 'Süvari Coffee', 'price' => 160, 'group_tr' => 'Sıcak İçecekler', 'group_en' => 'Hot Drinks'],
        ['name_tr' => 'Demleme Organik Yeşil Çay', 'name_en' => 'Brewed Organic Green Tea', 'price' => 200, 'group_tr' => 'Sıcak İçecekler', 'group_en' => 'Hot Drinks'],
        ['name_tr' => 'Demleme Ada Çayı', 'name_en' => 'Brewed Sage Tea', 'price' => 200, 'group_tr' => 'Sıcak İçecekler', 'group_en' => 'Hot Drinks'],
    ]],
    ['nargile', 'Nargile', 'Hookah', 'Aromalar: kavun, çilek, karpuz, üzüm, limon, portakal, nane, sakız, elma, şeftali', 'Flavours: melon, strawberry, watermelon, grape, lemon, orange, mint, mastic, apple, peach', 'hookah', [
        ['name_tr' => 'Cove 66', 'name_en' => 'Cove 66', 'description_tr' => '6 çeşit tat, nane', 'description_en' => '6 flavours, mint', 'price' => 720, 'group_tr' => 'Karışımlar', 'group_en' => 'Blends'],
        ['name_tr' => 'Cady Killer', 'name_en' => 'Cady Killer', 'description_tr' => 'Şeftali, mango, nane', 'description_en' => 'Peach, mango, mint', 'price' => 720, 'group_tr' => 'Karışımlar', 'group_en' => 'Blends'],
        ['name_tr' => 'İzmir Romantik', 'name_en' => 'İzmir Romantik', 'description_tr' => 'Karpuz, çilek, portakal, nane', 'description_en' => 'Watermelon, strawberry, orange, mint', 'price' => 720, 'group_tr' => 'Karışımlar', 'group_en' => 'Blends'],
        ['name_tr' => 'Bubble Gum', 'name_en' => 'Bubble Gum', 'description_tr' => 'Şekerli sakız', 'description_en' => 'Sweet bubble gum', 'price' => 720, 'group_tr' => 'Karışımlar', 'group_en' => 'Blends'],
        ['name_tr' => 'Blue Berry', 'name_en' => 'Blueberry', 'description_tr' => 'Yaban mersini', 'description_en' => 'Blueberry', 'price' => 720, 'group_tr' => 'Karışımlar', 'group_en' => 'Blends'],
        ['name_tr' => 'Cola Dragon', 'name_en' => 'Cola Dragon', 'description_tr' => 'Kola, enerji içeceği', 'description_en' => 'Cola, energy drink', 'price' => 720, 'group_tr' => 'Karışımlar', 'group_en' => 'Blends'],
        ['name_tr' => 'Mango Tango', 'name_en' => 'Mango Tango', 'description_tr' => 'Mango, tutku meyvesi', 'description_en' => 'Mango, passion fruit', 'price' => 720, 'group_tr' => 'Karışımlar', 'group_en' => 'Blends'],
        ['name_tr' => 'Two Apple', 'name_en' => 'Two Apple', 'description_tr' => 'Anason', 'description_en' => 'Aniseed', 'price' => 720, 'group_tr' => 'Karışımlar', 'group_en' => 'Blends'],
        ['name_tr' => 'Babyloon Mix', 'name_en' => 'Babyloon Mix', 'price' => 720, 'group_tr' => 'Karışımlar', 'group_en' => 'Blends'],
        ['name_tr' => 'Ejoy', 'name_en' => 'Ejoy', 'description_tr' => 'Karpuz, kremalı yaban mersini', 'description_en' => 'Watermelon, creamy blueberry', 'price' => 0, 'group_tr' => 'Jibiar', 'group_en' => 'Jibiar'],
        ['name_tr' => 'Plombir', 'name_en' => 'Plombir', 'description_tr' => 'Buzlu vanilyalı çikolatalı dondurma', 'description_en' => 'Iced vanilla-chocolate ice cream', 'price' => 0, 'group_tr' => 'Jibiar', 'group_en' => 'Jibiar'],
        ['name_tr' => 'Amrmıo', 'name_en' => 'Amrmıo', 'description_tr' => 'Ananas, buz, muz, nane', 'description_en' => 'Pineapple, ice, banana, mint', 'price' => 0, 'group_tr' => 'Jibiar', 'group_en' => 'Jibiar'],
        ['name_tr' => 'Chocolate Chill', 'name_en' => 'Chocolate Chill', 'description_tr' => 'Çikolata, mix nane', 'description_en' => 'Chocolate, mint mix', 'price' => 0, 'group_tr' => 'Jibiar', 'group_en' => 'Jibiar'],
        ['name_tr' => 'İnfrn night', 'name_en' => 'İnfrn Night', 'description_tr' => 'Yaban mersini, salkım meyveler, nane', 'description_en' => 'Blueberry, berries, mint', 'price' => 0, 'group_tr' => 'Jibiar', 'group_en' => 'Jibiar'],
        ['name_tr' => 'Master Mix', 'name_en' => 'Master Mix', 'description_tr' => 'Ahududu, portakal, şeftali, yaban mersini', 'description_en' => 'Raspberry, orange, peach, blueberry', 'price' => 0, 'group_tr' => 'Jibiar', 'group_en' => 'Jibiar'],
        ['name_tr' => 'Meyve Başlık', 'name_en' => 'Fruit Bowl Head', 'price' => 900, 'group_tr' => 'Ekstralar', 'group_en' => 'Extras'],
        ['name_tr' => 'Başlık Değişimi', 'name_en' => 'Bowl Change', 'price' => 330, 'group_tr' => 'Ekstralar', 'group_en' => 'Extras'],
        ['name_tr' => 'Nargile Anason', 'name_en' => 'Aniseed Hookah', 'price' => 750, 'group_tr' => 'Ekstralar', 'group_en' => 'Extras'],
        ['name_tr' => 'Nargile Menü', 'name_en' => 'Hookah Menu', 'price' => 950, 'group_tr' => 'Ekstralar', 'group_en' => 'Extras'],
    ]],
    ['oyun', 'Oyunlar', 'Games', 'Tavla, kart, Monopoly, Scrabble, domino, okey, Tabu, Jenga, satranç', 'Backgammon, cards, Monopoly, Scrabble, dominoes, okey, Taboo, Jenga, chess', 'dice', [
        ['name_tr' => 'Okey', 'name_en' => 'Okey (Rummikub)', 'description_tr' => 'Okey ücreti', 'description_en' => 'Okey game fee', 'price' => 200],
    ]],
];
